install.packages(
		 c(
		   "markdown",
		   "gt", 
		   "DT", 
		   "kableExtra", 
		   "flextable", 
		   "huxtable", 
		   "reactable", 
		   "formattable", 
		   "pixiedust", 
		   "agricolae", 
		   "car",
		   "plotly"
		   "tinytex"
		   "quarto"
		 )
)

tinytex::install_tinytex(force=TRUE)
